In [ ]:
import pandas as pd

# Update the path to match where you placed your files in Google Drive
data_dir = '/content/drive/MyDrive/Colab Notebooks/Ecommerce_data'

sales = pd.read_csv(f"{data_dir}/Sales.csv")
customers = pd.read_csv(f"{data_dir}/Customers.csv", encoding="latin1")
products = pd.read_csv(f"{data_dir}/Products.csv", encoding="latin1")
stores = pd.read_csv(f"{data_dir}/Stores.csv")
exchange_rates = pd.read_csv(f"{data_dir}/Exchange_Rates.csv")

In [ ]:
sales.shape

(62884, 9)

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  object
 3   Delivery Date  13165 non-null  object
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: int64(6), object(3)
memory usage: 4.3+ MB

In [ ]:
sales["Order Date"] = pd.to_datetime(sales["Order Date"])
sales["Delivery Date"] = pd.to_datetime(sales["Delivery Date"])

In [ ]:
print(sales["Order Date"].min())
print(sales["Order Date"].max())

2016-01-01 00:00:00
2021-02-20 00:00:00

In [ ]:
sales.duplicated().sum()

np.int64(0)

In [ ]:
sales.duplicated(
    subset=["Order Number", "Line Item"]
).sum()

np.int64(0)

In [ ]:
sales.isna().sum()

Order Number         0
Line Item            0
Order Date           0
Delivery Date    49719
CustomerKey          0
StoreKey             0
ProductKey           0
Quantity             0
Currency Code        0
dtype: int64

In [ ]:
sales.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD
3,366002,1,2016-01-01,2016-01-12,266019,0,1106,7,CAD
4,366002,2,2016-01-01,2016-01-12,266019,0,373,1,CAD

In [ ]:
sales["Currency Code"].value_counts()

Currency Code
USD    33767
EUR    12621
GBP     8140
CAD     5415
AUD     2941
Name: count, dtype: int64

In [ ]:
products.head()

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

In [ ]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   object
 5   Unit Price USD  2517 non-null   object
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   object
dtypes: int64(3), object(7)
memory usage: 196.8+ KB

In [ ]:
products.columns

Index(['ProductKey', 'Product Name', 'Brand', 'Color', 'Unit Cost USD',
       'Unit Price USD', 'SubcategoryKey', 'Subcategory', 'CategoryKey',
       'Category'],
      dtype='object')

In [ ]:
exchange_rates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11215 entries, 0 to 11214
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      11215 non-null  object
 1   Currency  11215 non-null  object
 2   Exchange  11215 non-null  float64
dtypes: float64(1), object(2)
memory usage: 263.0+ KB

In [ ]:
exchange_rates.head()

       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415

In [ ]:
exchange_rates["Date"] = pd.to_datetime(exchange_rates["Date"])

In [ ]:
exchange_rates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11215 entries, 0 to 11214
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      11215 non-null  datetime64[ns]
 1   Currency  11215 non-null  object
 2   Exchange  11215 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 263.0+ KB

In [ ]:
print(exchange_rates["Date"].min())
print(exchange_rates["Date"].max())

2015-01-01 00:00:00
2021-02-20 00:00:00

In [ ]:
sales[["Order Date", "Currency Code"]].drop_duplicates().shape

(6004, 2)

In [ ]:
exchange_rates[["Date", "Currency"]].drop_duplicates().shape

(11215, 2)

In [ ]:
check = sales[
    ["Order Date", "Currency Code"]
].drop_duplicates().merge(
    exchange_rates[
        ["Date", "Currency"]
    ].drop_duplicates(),
    left_on=["Order Date", "Currency Code"],
    right_on=["Date", "Currency"],
    how="left",
    indicator=True
)

In [ ]:
check["_merge"].value_counts()

_merge
both          6004
left_only        0
right_only       0
Name: count, dtype: int64

In [ ]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StoreKey       67 non-null     int64
 1   Country        67 non-null     object
 2   State          67 non-null     object
 3   Square Meters  66 non-null     float64
 4   Open Date      67 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.7+ KB

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15256 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  object
dtypes: int64(1), object(9)
memory usage: 1.2+ MB

In [ ]:
sales["Order Date"] = pd.to_datetime(sales["Order Date"])
sales["Delivery Date"] = pd.to_datetime(sales["Delivery Date"])

stores["Open Date"] = pd.to_datetime(stores["Open Date"])

customers["Birthday"] = pd.to_datetime(customers["Birthday"])

exchange_rates["Date"] = pd.to_datetime(exchange_rates["Date"])

In [ ]:
products["Unit Cost USD"] = (
    products["Unit Cost USD"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype(float)
)

products["Unit Price USD"] = (
    products["Unit Price USD"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype(float)
)

In [ ]:
stores[stores["Square Meters"].isna()]

    StoreKey Country   State  Square Meters  Open Date
66         0  Online  Online            NaN 2010-01-01

In [ ]:
customers[customers["State Code"].isna()]

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
5304,729681,Female,Rossana Padovesi,Polvica,NaN,Napoli,80035,Italy,Europe,1981-04-18
5316,732289,Male,Indro Piccio,Varcaturo,NaN,Napoli,80014,Italy,Europe,1949-02-24
5372,742042,Male,Amaranto Loggia,Casaferro,NaN,Napoli,80034,Italy,Europe,1936-03-14
5377,742886,Female,Edmonda Capon,Terzigno,NaN,Napoli,80040,Italy,Europe,1963-08-06
5378,743343,Female,Ambra Sagese,Pomigliano D'Arco,NaN,Napoli,80038,Italy,Europe,1961-01-05
5485,759705,Male,Callisto Lo Duca,Casilli,NaN,Napoli,80047,Italy,Europe,1976-08-28
5525,765589,Male,Michelino Lucchesi,Pompei Scavi,NaN,Napoli,80045,Italy,Europe,1947-11-13
5531,766410,Male,Adelmio Beneventi,Licola,NaN,Napoli,80078,Italy,Europe,1940-01-13
5631,781667,Female,Ilda Manna,Napoli,NaN,Napoli,80134,Italy,Europe,1977-05-08
5695,789177,Male,Calogero Folliero,Mariglianella,NaN,Napoli,80030,Italy,Europe,2000-03-03

In [ ]:
sales["ProductKey"].isin(products["ProductKey"]).value_counts()

ProductKey
True    62884
Name: count, dtype: int64

In [ ]:
sales["CustomerKey"].isin(customers["CustomerKey"]).value_counts()

CustomerKey
True    62884
Name: count, dtype: int64

In [ ]:
sales["StoreKey"].isin(stores["StoreKey"]).value_counts()

StoreKey
True    62884
Name: count, dtype: int64

In [ ]:
sales_analysis = sales.merge(
    products,
    on="ProductKey",
    how="left"
)

In [ ]:
sales_analysis.shape

(62884, 18)

In [ ]:
sales_analysis.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD,Contoso Lens Adapter M450 White,Contoso,White,31.27,68.00,406,Cameras & Camcorders Accessories,4,Cameras and camcorders
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD,A. Datum SLR Camera X136 Silver,A. Datum,Silver,141.47,427.00,402,Digital SLR Cameras,4,Cameras and camcorders
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD,Fabrikam Microwave 1.5CuFt X1100 Black,Fabrikam,Black,220.64,665.94,803,Microwaves,8,Home Appliances
3,366002,1,2016-01-01,2016-01-12,266019,0,1106,7,CAD,Contoso SLR Camera M146 Orange,Contoso,Orange,148.08,322.00,402,Digital SLR Cameras,4,Cameras and camcorders
4,366002,2,2016-01-01,2016-01-12,266019,0,373,1,CAD,Adventure Works Laptop8.9 E0890 White,Adventure Works,White,166.20,326.00,301,Laptops,3,Computers

In [ ]:
sales_analysis = sales_analysis.merge(
    customers,
    on="CustomerKey",
    how="left"
)

In [ ]:
sales_analysis.shape

(62884, 27)

In [ ]:
sales_analysis = sales_analysis.merge(
    stores,
    on="StoreKey",
    how="left"
)

In [ ]:
sales_analysis.shape

(62884, 31)

In [ ]:
sales_analysis.columns

Index(['Order Number', 'Line Item', 'Order Date', 'Delivery Date',
       'CustomerKey', 'StoreKey', 'ProductKey', 'Quantity', 'Currency Code',
       'Product Name', 'Brand', 'Color', 'Unit Cost USD', 'Unit Price USD',
       'SubcategoryKey', 'Subcategory', 'CategoryKey', 'Category', 'Gender',
       'Name', 'City', 'State Code', 'State_x', 'Zip Code', 'Country_x',
       'Continent', 'Birthday', 'Country_y', 'State_y', 'Square Meters',
       'Open Date'],
      dtype='object')

In [ ]:
sales_analysis.head(3)

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code,Product Name,...,State Code,State_x,Zip Code,Country_x,Continent,Birthday,Country_y,State_y,Square Meters,Open Date
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD,Contoso Lens Adapter M450 White,...,ON,Ontario,N5W 5K6,Canada,North America,1971-03-23,Canada,Nunavut,1210.0,2015-04-04
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD,A. Datum SLR Camera X136 Silver,...,CA,California,93602,United States,North America,1995-11-20,Online,Online,NaN,2010-01-01
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD,Fabrikam Microwave 1.5CuFt X1100 Black,...,CA,California,93602,United States,North America,1995-11-20,Online,Online,NaN,2010-01-01

In [ ]:
sales_analysis = sales_analysis.rename(columns={
    "Country_x": "Customer Country",
    "Country_y": "Store Country",
    "State_x": "Customer State",
    "State_y": "Store State"
})

In [ ]:
sales_analysis.columns

Index(['Order Number', 'Line Item', 'Order Date', 'Delivery Date',
       'CustomerKey', 'StoreKey', 'ProductKey', 'Quantity', 'Currency Code',
       'Product Name', 'Brand', 'Color', 'Unit Cost USD', 'Unit Price USD',
       'SubcategoryKey', 'Subcategory', 'CategoryKey', 'Category', 'Gender',
       'Name', 'City', 'State Code', 'Customer State', 'Zip Code',
       'Customer Country', 'Continent', 'Birthday', 'Store Country',
       'Store State', 'Square Meters', 'Open Date'],
      dtype='object')

In [ ]:
sales_analysis["Revenue USD"] = (
    sales_analysis["Quantity"] *
    sales_analysis["Unit Price USD"]
)

In [ ]:
sales_analysis[
    ["Quantity", "Unit Price USD", "Revenue USD"]
].head()

   Quantity  Unit Price USD  Revenue USD
0         1           68.00        68.00
1         2          427.00       854.00
2         1          665.94       665.94
3         7          322.00      2254.00
4         1          326.00       326.00

In [ ]:
sales_analysis["Cost USD"] = (
    sales_analysis["Quantity"] *
    sales_analysis["Unit Cost USD"]
)

In [ ]:
sales_analysis["Profit USD"] = (
    sales_analysis["Revenue USD"] -
    sales_analysis["Cost USD"]
)

In [ ]:
sales_analysis["Profit Margin %"] = (
    sales_analysis["Profit USD"] /
    sales_analysis["Revenue USD"]
) * 100

In [ ]:
sales_analysis[
    ["Revenue USD", "Cost USD", "Profit USD", "Profit Margin %"]
].head()

   Revenue USD  Cost USD  Profit USD  Profit Margin %
0        68.00     31.27       36.73        54.014706
1       854.00    282.94      571.06        66.868852
2       665.94    220.64      445.30        66.867886
3      2254.00   1036.56     1217.44        54.012422
4       326.00    166.20      159.80        49.018405

In [ ]:
sales_analysis["Profit Margin %"] = sales_analysis["Profit Margin %"].round(2)

In [ ]:
sales_analysis[
    ["Quantity", "Revenue USD", "Cost USD", "Profit USD", "Profit Margin %"]
].describe()

           Quantity   Revenue USD      Cost USD    Profit USD  Profit Margin %
count  62884.000000  62884.000000  62884.000000  62884.000000     62884.000000
mean       3.144790    886.640156    367.228408    519.411748        54.904309
std        2.256371   1648.480286    614.548869   1052.204029         6.413317
min        1.000000      0.950000      0.480000      0.470000        48.950000
25%        1.000000    115.000000     52.880000     61.560000        49.020000
50%        2.000000    360.000000    164.160000    194.440000        54.010000
75%        4.000000    969.000000    423.080000    540.140000        54.020000
max       10.000000  31999.900000  10602.200000  21397.700000        66.890000

In [ ]:
category_summary = sales_analysis.groupby("Category").agg(
    Revenue=("Revenue USD", "sum"),
    Cost=("Cost USD", "sum"),
    Profit=("Profit USD", "sum")
)

In [ ]:
category_summary

                                   Revenue        Cost       Profit
Category
Audio                           3169627.74  1341775.97   1827851.77
Cameras and camcorders          6520168.02  2600367.03   3919800.99
Cell phones                     6183791.22  2685164.68   3498626.54
Computers                      19301595.46  8024147.56  11277447.90
Games and Toys                   724829.43   328160.66    396668.77
Home Appliances                10795478.59  4499139.74   6296338.85
Music, Movies and Audio Books   3131006.44  1221747.27   1909259.17
TV and Video                    5928982.69  2392288.30   3536694.39

In [ ]:
category_summary["Profit Margin %"] = (
    category_summary["Profit"] /
    category_summary["Revenue"] *
    100
)

In [ ]:
category_summary.sort_values(
    "Profit Margin %",
    ascending=False
)

,Revenue,Cost,Profit,Profit Margin %
Category,,,,
"Music, Movies and Audio Books",3131006.44,1221747.27,1909259.17,60.979088
Cameras and camcorders,6520168.02,2600367.03,3919800.99,60.118098
TV and Video,5928982.69,2392288.30,3536694.39,59.650948
Computers,19301595.46,8024147.56,11277447.90,58.427543
Home Appliances,10795478.59,4499139.74,6296338.85,58.323851
Audio,3169627.74,1341775.97,1827851.77,57.667711
Cell phones,6183791.22,2685164.68,3498626.54,56.577372
Games and Toys,724829.43,328160.66,396668.77,54.725809

In [ ]:
product_summary = sales_analysis.groupby(
    ["Product Name", "ProductKey", "Brand", "Category"]
).agg(
    Quantity=("Quantity", "sum"),
    Revenue=("Revenue USD", "sum"),
    Cost=("Cost USD", "sum"),
    Profit=("Profit USD", "sum")
)

In [ ]:
product_summary

,,,,Quantity,Revenue,Cost,Profit
Product Name,ProductKey,Brand,Category,,,,
A. Datum Advanced Digital Camera M300 Azure,1037,A. Datum,Cameras and camcorders,31,5843.50,2687.08,3156.42
A. Datum Advanced Digital Camera M300 Black,953,A. Datum,Cameras and camcorders,34,6409.00,2947.12,3461.88
A. Datum Advanced Digital Camera M300 Green,1023,A. Datum,Cameras and camcorders,41,7728.50,3553.88,4174.62
A. Datum Advanced Digital Camera M300 Grey,967,A. Datum,Cameras and camcorders,49,9236.50,4247.32,4989.18
A. Datum Advanced Digital Camera M300 Orange,1009,A. Datum,Cameras and camcorders,46,8671.00,3987.28,4683.72
...,...,...,...,...,...,...,...
WWI Wireless Transmitter and Bluetooth Headphones X250 Black,111,Wide World Importers,Audio,266,66497.34,22032.78,44464.56
WWI Wireless Transmitter and Bluetooth Headphones X250 Blue,112,Wide World Importers,Audio,220,54997.80,18222.60,36775.20
WWI Wireless Transmitter and Bluetooth Headphones X250 Red,114,Wide World Importers,Audio,296,73997.04,24517.68,49479.36
WWI Wireless Transmitter and Bluetooth Headphones X250 Silver,115,Wide World Importers,Audio,277,69247.23,22943.91,46303.32
WWI Wireless Transmitter and Bluetooth Headphones X250 White,113,Wide World Importers,Audio,292,72997.08,24186.36,48810.72

In [ ]:
product_summary.sort_values(
    "Revenue",
    ascending=False
).head(10)

,,,,Quantity,Revenue,Cost,Profit
Product Name,ProductKey,Brand,Category,,,,
WWI Desktop PC2.33 X2330 Black,444,Wide World Importers,Computers,550,505450.00,167464.00,337986.00
Adventure Works Desktop PC2.33 XD233 Silver,416,Adventure Works,Computers,481,466089.00,154425.05,311663.95
Adventure Works Desktop PC2.33 XD233 Brown,428,Adventure Works,Computers,479,464151.00,153782.95,310368.05
Adventure Works Desktop PC2.33 XD233 Black,422,Adventure Works,Computers,462,447678.00,148325.10,299352.90
Adventure Works Desktop PC2.33 XD233 White,433,Adventure Works,Computers,451,437019.00,144793.55,292225.45
WWI Desktop PC2.33 X2330 White,455,Wide World Importers,Computers,462,424578.00,140669.76,283908.24
WWI Desktop PC2.33 X2330 Brown,450,Wide World Importers,Computers,460,422740.00,140060.80,282679.20
"Adventure Works 52"" LCD HDTV X590 White",147,Adventure Works,TV and Video,136,394398.64,130671.52,263727.12
"Adventure Works 52"" LCD HDTV X590 Black",146,Adventure Works,TV and Video,129,374098.71,123945.78,250152.93
WWI Desktop PC2.33 X2330 Silver,438,Wide World Importers,Computers,392,360248.00,119356.16,240891.84

In [ ]:
product_summary.sort_values(
    "Profit",
    ascending=False
).head(10)

,,,,Quantity,Revenue,Cost,Profit
Product Name,ProductKey,Brand,Category,,,,
WWI Desktop PC2.33 X2330 Black,444,Wide World Importers,Computers,550,505450.00,167464.00,337986.00
Adventure Works Desktop PC2.33 XD233 Silver,416,Adventure Works,Computers,481,466089.00,154425.05,311663.95
Adventure Works Desktop PC2.33 XD233 Brown,428,Adventure Works,Computers,479,464151.00,153782.95,310368.05
Adventure Works Desktop PC2.33 XD233 Black,422,Adventure Works,Computers,462,447678.00,148325.10,299352.90
Adventure Works Desktop PC2.33 XD233 White,433,Adventure Works,Computers,451,437019.00,144793.55,292225.45
WWI Desktop PC2.33 X2330 White,455,Wide World Importers,Computers,462,424578.00,140669.76,283908.24
WWI Desktop PC2.33 X2330 Brown,450,Wide World Importers,Computers,460,422740.00,140060.80,282679.20
"Adventure Works 52"" LCD HDTV X590 White",147,Adventure Works,TV and Video,136,394398.64,130671.52,263727.12
"Adventure Works 52"" LCD HDTV X590 Black",146,Adventure Works,TV and Video,129,374098.71,123945.78,250152.93
WWI Desktop PC2.33 X2330 Silver,438,Wide World Importers,Computers,392,360248.00,119356.16,240891.84

In [ ]:
product_summary["Profit Margin %"] = (
    product_summary["Profit"] /
    product_summary["Revenue"] *
    100
)

In [ ]:
product_summary.sort_values(
    "Profit Margin %",
    ascending=False
).head(10)

,,,,Quantity,Revenue,Cost,Profit,Profit Margin %
Product Name,ProductKey,Brand,Category,,,,,
Contoso DVD 60 DVD Storage Binder L20 Black,1630,Contoso,"Music, Movies and Audio Books",254,5814.06,1925.32,3888.74,66.885103
Contoso DVD 60 DVD Storage Binder L20 Red,1640,Contoso,"Music, Movies and Audio Books",266,6088.74,2016.28,4072.46,66.885103
SV DVD 60 DVD Storage Binder L20 Black,1585,Southridge Video,"Music, Movies and Audio Books",305,6981.45,2311.90,4669.55,66.885103
SV DVD 60 DVD Storage Binder L20 Silver,1590,Southridge Video,"Music, Movies and Audio Books",310,7095.90,2349.80,4746.10,66.885103
Contoso DVD 60 DVD Storage Binder L20 Silver,1635,Contoso,"Music, Movies and Audio Books",311,7118.79,2357.38,4761.41,66.885103
SV DVD 60 DVD Storage Binder L20 Red,1595,Southridge Video,"Music, Movies and Audio Books",277,6340.53,2099.66,4240.87,66.885103
Contoso Centrex Phone System L10 White,1359,Contoso,Cell phones,69,2966.31,982.56,1983.75,66.876018
Contoso Centrex Phone System L10 Black,1326,Contoso,Cell phones,62,2665.38,882.88,1782.50,66.876018
Contoso Centrex Phone System L10 Grey,1392,Contoso,Cell phones,59,2536.41,840.16,1696.25,66.876018
Contoso Behind Centrex X15 White,1361,Contoso,Cell phones,74,3699.26,1225.44,2473.82,66.873375

In [ ]:
product_summary.sort_values(
    "Quantity",
    ascending=False
).head(10)

,,,,Quantity,Revenue,Cost,Profit,Profit Margin %
Product Name,ProductKey,Brand,Category,,,,,
WWI Desktop PC2.33 X2330 Black,444,Wide World Importers,Computers,550,505450.00,167464.00,337986.00,66.868335
WWI Desktop PC1.80 E1800 White,458,Wide World Importers,Computers,538,123686.20,63058.98,60627.22,49.016964
Adventure Works Desktop PC2.30 MD230 White,434,Adventure Works,Computers,521,312079.00,143514.66,168564.34,54.013356
Adventure Works Desktop PC1.60 ED160 Black,424,Adventure Works,Computers,521,140643.95,71705.23,68938.72,49.016485
Adventure Works Desktop PC1.80 ED180 Black,425,Adventure Works,Computers,520,191880.00,97827.60,94052.40,49.016260
Adventure Works Desktop PC2.30 MD230 Black,423,Adventure Works,Computers,514,307886.00,141586.44,166299.56,54.013356
WWI Desktop PC1.60 E1600 Black,446,Wide World Importers,Computers,509,111954.55,57079.26,54875.29,49.015685
WWI Desktop PC1.60 E1600 Silver,440,Wide World Importers,Computers,507,111514.65,56854.98,54659.67,49.015685
WWI Desktop PC1.80 E1801 Black,448,Wide World Importers,Computers,505,136299.50,69488.00,66811.50,49.018155
WWI Desktop PC1.60 E1600 Red,452,Wide World Importers,Computers,505,111074.75,56630.70,54444.05,49.015685

In [ ]:
product_summary["Avg Selling Price"] = (
    product_summary["Revenue"] /
    product_summary["Quantity"]
)

In [ ]:
product_summary.sort_values(
    "Avg Selling Price",
    ascending=False
).head(10)

,,,,Quantity,Revenue,Cost,Profit,Profit Margin %,Avg Selling Price
Product Name,ProductKey,Brand,Category,,,,,,
Litware Refrigerator 24.7CuFt X980 White,1939,Litware,Home Appliances,7,22399.93,7421.54,14978.39,66.868021,3199.99
Fabrikam Refrigerator 24.7CuFt X9800 Orange,1933,Fabrikam,Home Appliances,33,105599.67,34987.26,70612.41,66.868021,3199.99
Litware Refrigerator 24.7CuFt X980 Silver,1951,Litware,Home Appliances,32,102399.68,33927.04,68472.64,66.868021,3199.99
Fabrikam Refrigerator 24.7CuFt X9800 Blue,1921,Fabrikam,Home Appliances,27,86399.73,28625.94,57773.79,66.868021,3199.99
Fabrikam Refrigerator 24.7CuFt X9800 Silver,1909,Fabrikam,Home Appliances,34,108799.66,36047.48,72752.18,66.868021,3199.99
Litware Refrigerator 24.7CuFt X980 Blue,1963,Litware,Home Appliances,15,47999.85,15903.30,32096.55,66.868021,3199.99
Litware Refrigerator 24.7CuFt X980 Brown,1945,Litware,Home Appliances,24,76799.76,25445.28,51354.48,66.868021,3199.99
Litware Refrigerator 24.7CuFt X980 Grey,1969,Litware,Home Appliances,24,76799.76,25445.28,51354.48,66.868021,3199.99
Fabrikam Refrigerator 24.7CuFt X9800 Green,1915,Fabrikam,Home Appliances,31,99199.69,32866.82,66332.87,66.868021,3199.99
Litware Refrigerator 24.7CuFt X980 Green,1957,Litware,Home Appliances,29,92799.71,30746.38,62053.33,66.868021,3199.99

In [ ]:
sales_analysis["Order Date"].dtype

dtype('<M8[ns]')

In [ ]:
sales_analysis["Year"] = sales_analysis["Order Date"].dt.year
sales_analysis["Month"] = sales_analysis["Order Date"].dt.month
sales_analysis["Month Name"] = sales_analysis["Order Date"].dt.month_name()
sales_analysis["Quarter"] = sales_analysis["Order Date"].dt.quarter

In [ ]:
yearly_sales = sales_analysis.groupby("Year").agg(
    Revenue=("Revenue USD", "sum"),
    Cost=("Cost USD", "sum"),
    Profit=("Profit USD", "sum"),
    Quantity=("Quantity", "sum")
).reset_index()

yearly_sales["Profit Margin %"] = (
    yearly_sales["Profit"] /
    yearly_sales["Revenue"] * 100
).round(2)

yearly_sales

   Year      Revenue        Cost       Profit  Quantity  Profit Margin %
0  2016   6946793.56  2839793.09   4107000.47     21761            59.12
1  2017   7421422.27  3084358.21   4337064.06     24798            58.44
2  2018  12788960.66  5323999.55   7464961.11     44498            58.37
3  2019  18264382.48  7566643.58  10697738.90     68440            58.57
4  2020   9294632.14  3847171.99   5447460.15     34463            58.61
5  2021   1039288.48   430824.79    608463.69      3797            58.55

In [ ]:
monthly_sales = sales_analysis.groupby(
    ["Year", "Month"]
).agg(
    Revenue=("Revenue USD", "sum"),
    Profit=("Profit USD", "sum")
).reset_index()

monthly_sales

    Year  Month    Revenue     Profit
0   2016      1  649918.78  388268.96
1   2016      2  891098.30  531722.75
2   2016      3  338407.36  203506.99
3   2016      4  110591.63   66231.19
4   2016      5  595986.18  356049.32
..   ...    ...        ...        ...
57  2020     10  245647.59  141098.51
58  2020     11  256701.02  149679.25
59  2020     12  651526.44  384657.66
60  2021      1  513021.58  300479.71
61  2021      2  526266.90  307983.98

[62 rows x 4 columns]

In [ ]:
customer_summary = sales_analysis.groupby(
    ["CustomerKey", "Name", "City", "Customer State", "Customer Country"]
).agg(
    Orders=("Order Number", "nunique"),
    Quantity=("Quantity", "sum"),
    Revenue=("Revenue USD", "sum"),
    Profit=("Profit USD", "sum")
).reset_index()

In [ ]:
customer_summary["Profit Margin %"] = (
    customer_summary["Profit"] /
    customer_summary["Revenue"] * 100
).round(2)

In [ ]:
customer_summary.sort_values(
    "Revenue",
    ascending=False
).head(10)

,CustomerKey,Name,City,Customer State,Customer Country,Orders,Quantity,Revenue,Profit,Profit Margin %
9371,1702221,Matthew Flemming,Anaheim,California,United States,9,75,61871.70,39606.02,64.01
10515,1884663,Karen Jones,Lacassine,Louisiana,United States,3,30,43517.80,28819.96,66.23
11072,1969704,Zrina Topic,Lyerly,Georgia,United States,7,60,42788.04,26008.23,60.78
2743,535496,Stefanie Hartmann,Geltendorf,Freistaat Bayern,Germany,3,35,41521.53,26957.37,64.92
2840,551036,Stephan Rothstein,Lütjenwestedt,Schleswig-Holstein,Germany,4,36,40556.54,26716.09,65.87
3664,723572,Gaspare Trevisan,Galdo Degli Alburni,Salerno,Italy,14,124,40225.01,23440.78,58.27
1175,262871,Roy Le,Merrickville,Ontario,Canada,3,32,38813.88,23986.19,61.80
10795,1928466,Dennis Weissmuller,Philadelphia,Pennsylvania,United States,4,40,38191.06,24054.60,62.98
8116,1503831,Virgie Takacs,Walworth,Wisconsin,United States,3,29,37319.88,22881.47,61.31
7275,1373561,Ollie Davis,Springdale,Arkansas,United States,5,62,36817.28,22954.48,62.35

In [ ]:
customer_summary.sort_values(
    "Profit",
    ascending=False
).head(10)

,CustomerKey,Name,City,Customer State,Customer Country,Orders,Quantity,Revenue,Profit,Profit Margin %
9371,1702221,Matthew Flemming,Anaheim,California,United States,9,75,61871.70,39606.02,64.01
10515,1884663,Karen Jones,Lacassine,Louisiana,United States,3,30,43517.80,28819.96,66.23
2743,535496,Stefanie Hartmann,Geltendorf,Freistaat Bayern,Germany,3,35,41521.53,26957.37,64.92
2840,551036,Stephan Rothstein,Lütjenwestedt,Schleswig-Holstein,Germany,4,36,40556.54,26716.09,65.87
11072,1969704,Zrina Topic,Lyerly,Georgia,United States,7,60,42788.04,26008.23,60.78
10795,1928466,Dennis Weissmuller,Philadelphia,Pennsylvania,United States,4,40,38191.06,24054.60,62.98
1175,262871,Roy Le,Merrickville,Ontario,Canada,3,32,38813.88,23986.19,61.80
3664,723572,Gaspare Trevisan,Galdo Degli Alburni,Salerno,Italy,14,124,40225.01,23440.78,58.27
4508,879649,Esin Holman,s-Gravenpolder,Zeeland,Netherlands,4,42,35710.61,23282.10,65.20
7275,1373561,Ollie Davis,Springdale,Arkansas,United States,5,62,36817.28,22954.48,62.35

In [ ]:
customer_summary["AOV"] = (
    customer_summary["Revenue"] /
    customer_summary["Orders"]
).round(2)

In [ ]:
customer_summary.sort_values(
    "AOV",
    ascending=False
).head(10)

,CustomerKey,Name,City,Customer State,Customer Country,Orders,Quantity,Revenue,Profit,Profit Margin %,AOV
9106,1661166,Bryan Charles,Pottsville,Pennsylvania,United States,1,11,32056.89,21428.48,66.85,32056.89
3650,720281,Vera Onio,Marmora,Cuneo,Italy,1,13,29429.87,19629.24,66.70,29429.87
8058,1493760,Eliza Norwood,Bon Wier,Texas,United States,1,19,29002.99,19075.18,65.77,29002.99
5544,1082222,Rhys Young,HORSEHAY,Telford and Wrekin,United Kingdom,1,19,25865.14,17287.54,66.84,25865.14
7213,1363803,Erin Stevens,Turner,Maine,United States,1,24,25608.74,16922.81,66.08,25608.74
4573,891896,Nour Walburg,Sassenheim,Zuid-Holland,Netherlands,1,24,25449.13,16948.97,66.60,25449.13
8088,1499604,Richard Green,Chicago,Illinois,United States,1,30,25447.00,15948.05,62.67,25447.00
11798,2086548,Augustyn Czerwinski,Schiller Park,Illinois,United States,1,19,23268.90,15335.15,65.90,23268.90
5927,1150424,Kian Sims,HALSTEAD,Braintree,United Kingdom,1,7,22399.93,14978.39,66.87,22399.93
5486,1069911,Declan O'Donnell,EAST BARKWITH,Lincoln,United Kingdom,1,29,20970.95,12486.53,59.54,20970.95

In [ ]:
country_summary = sales_analysis.groupby(
    "Customer Country"
).agg(
    Revenue=("Revenue USD", "sum"),
    Profit=("Profit USD", "sum"),
    Quantity=("Quantity", "sum"),
    Customers=("CustomerKey", "nunique")
).reset_index()

country_summary["Profit Margin %"] = (
    country_summary["Profit"] /
    country_summary["Revenue"] * 100
).round(2)

country_summary.sort_values(
    "Revenue",
    ascending=False
)

,Customer Country,Revenue,Profit,Quantity,Customers,Profit Margin %
7,United States,29871631.17,17490924.05,106407,5706,58.55
6,United Kingdom,7084088.12,4133800.81,25298,1570,58.35
3,Germany,5414149.80,3185916.46,18943,1150,58.84
1,Canada,4724334.63,2755738.22,16793,1179,58.33
0,Australia,2708137.61,1597300.18,9209,780,58.98
4,Italy,2475645.77,1450851.09,8470,530,58.60
5,Netherlands,1962154.27,1154644.08,7252,534,58.85
2,France,1515338.22,893513.49,5385,438,58.96

In [ ]:
store_summary = sales_analysis.groupby(
    ["StoreKey", "Store Country", "Store State"]
).agg(
    Revenue=("Revenue USD", "sum"),
    Profit=("Profit USD", "sum"),
    Quantity=("Quantity", "sum"),
    Orders=("Order Number", "nunique")
).reset_index()

store_summary["Profit Margin %"] = (
    store_summary["Profit"] /
    store_summary["Revenue"] * 100
).round(2)

In [ ]:
store_summary.sort_values(
    "Revenue",
    ascending=False
).head(10)

,StoreKey,Store Country,Store State,Revenue,Profit,Quantity,Orders,Profit Margin %
0,0,Online,Online,11404324.63,6672692.64,41311,5580,58.51
48,55,United States,Nevada,1417885.41,830551.75,4826,622,58.58
44,50,United States,Kansas,1394738.06,819659.12,4773,605,58.77
47,54,United States,Nebraska,1384396.24,810300.06,4686,629,58.53
7,9,Canada,Northwest Territories,1336150.06,774757.55,4894,658,57.98
50,57,United States,New Mexico,1325611.89,784095.76,4407,605,59.15
40,45,United States,Connecticut,1318787.92,761271.82,4672,617,57.73
52,61,United States,South Carolina,1305684.43,764997.20,4771,624,58.59
51,59,United States,Oregon,1302272.44,754702.32,4674,619,57.95
55,64,United States,Washington DC,1259350.98,745283.99,4289,566,59.18

In [ ]:
total_revenue = sales_analysis["Revenue USD"].sum()
total_cost = sales_analysis["Cost USD"].sum()
total_profit = sales_analysis["Profit USD"].sum()
total_quantity = sales_analysis["Quantity"].sum()
total_orders = sales_analysis["Order Number"].nunique()
total_customers = sales_analysis["CustomerKey"].nunique()

overall_margin = (
    total_profit / total_revenue * 100
)

In [ ]:
print("Total Revenue:", total_revenue)
print("Total Cost:", total_cost)
print("Total Profit:", total_profit)
print("Profit Margin:", round(overall_margin, 2), "%")
print("Units Sold:", total_quantity)
print("Orders:", total_orders)
print("Customers:", total_customers)

Total Revenue: 55755479.589999996
Total Cost: 23092791.209999997
Total Profit: 32662688.380000003
Profit Margin: 58.58 %
Units Sold: 197757
Orders: 26326
Customers: 11887

In [ ]:
sales_analysis.columns.tolist()

['Order Number',
 'Line Item',
 'Order Date',
 'Delivery Date',
 'CustomerKey',
 'StoreKey',
 'ProductKey',
 'Quantity',
 'Currency Code',
 'Product Name',
 'Brand',
 'Color',
 'Unit Cost USD',
 'Unit Price USD',
 'SubcategoryKey',
 'Subcategory',
 'CategoryKey',
 'Category',
 'Gender',
 'Name',
 'City',
 'State Code',
 'Customer State',
 'Zip Code',
 'Customer Country',
 'Continent',
 'Birthday',
 'Store Country',
 'Store State',
 'Square Meters',
 'Open Date',
 'Revenue USD',
 'Cost USD',
 'Profit USD',
 'Profit Margin %',
 'Year',
 'Month',
 'Month Name',
 'Quarter']

In [ ]:
sales_analysis.to_csv(
    "ecommerce_sales_analysis.csv",
    index=False
)